### ISSUE TITLE
Error while publishing documentation

### ISSUE THREAD

**Issue by kunj-sangani** [ValoIntranet/doctor#9]
While executing doctor publish --url
ran into below error checked the documentation of M365cli and found that below command does not have | jq
The impact is from 
File:- doctor/src/commands/publish.ts 
Line number:- 316
[Link to command](https://pnp.github.io/cli-microsoft365/cmd/spo/page/page-column-list/)

![image](https://user-images.githubusercontent.com/25693207/102441528-77671780-4048-11eb-83ad-924836418fcd.png)

**Comment by estruyf** [comment]
It seems you do not have a required tool called `jq`: https://stedolan.github.io/jq/ - If you install it, it should start working.

I will take this as an enhancement to remove this dependency.

**Comment by estruyf** [comment]
@kunj-sangani just removed the `jq` dependency in the latest beta version. Feel free to test it out by installing the beta as follows: `npm i @valo/doctor@next -g`.

**Comment by kunj-sangani** [comment]
@estruyf 
Thanks I will fetch the beta version and test

**Comment by kunj-sangani** [comment]
@estruyf 
I tested the latest build and it worked 👍 

![image](https://user-images.githubusercontent.com/25693207/102529246-a374ae00-40c5-11eb-9fcb-2d9f7c55238b.png)

**Comment by estruyf** [comment]
Thanks for the update!

**Comment by garrytrinder** [comment]
Just ran into the `jq` issue, so bumped to use the `@next` version however its not resolved for me, using content from the sample.

```sh
[13:05:27] Authenticate to M365 with password [started]
[13:05:28] Authenticate to M365 with password [completed]
[13:05:28] Fetch all markdown files [started]
[13:05:28] Fetch all markdown files [completed]
[13:05:28] Process markdown files [started]
[13:05:28] → Started processing: index.md
[13:05:29] → Creating or updating the page in SharePoint for index.md
[13:05:33] Process markdown files [failed]
[13:05:33] → Command failed: localm365 spo page clientsidewebpart add --webUrl "https://cpsglobaldev.sharepoint.com/teams/ValoDoctor" --pageName "Valo-Doctor.aspx" --webPartId 1ef5ed11-ce7b-44be-bc5e-4abd55101d16 --webPartData '{"title":"doctor-placeholder","serverProcessedContent": {"searchablePlainTexts": {"code": "
\nYour content goes here ..."}},"dataVersion": "2.0","properties": {"displayPreview": true,"lineWrapping": true,"miniMap": {"enabled": false},"previewState": "Show","theme": "Monokai"}}'
Error: Specified webPartData is not a valid JSON string. Input: {"title":"doctor-placeholder","serverProcessedContent": {"searchablePlainTexts": {"code": "
\nYour content goes here ..."}},"dataVersion": "2.0","properties": {"displayPreview": true,"lineWrapping": true,"miniMap": {"enabled": false},"previewState": "Show","theme": "Monokai"}}. Error: SyntaxError: Unexpected token 
 in JSON at position 91

Error: Command failed: localm365 spo page clientsidewebpart add --webUrl "https://cpsglobaldev.sharepoint.com/teams/ValoDoctor" --pageName "Valo-Doctor.aspx" --webPartId 1ef5ed11-ce7b-44be-bc5e-4abd55101d16 --webPartData '{"title":"doctor-placeholder","serverProcessedContent": {"searchablePlainTexts": {"code": "
\nYour content goes here ..."}},"dataVersion": "2.0","properties": {"displayPreview": true,"lineWrapping": true,"miniMap": {"enabled": false},"previewState": "Show","theme": "Monokai"}}'
Error: Specified webPartData is not a valid JSON string. Input: {"title":"doctor-placeholder","serverProcessedContent": {"searchablePlainTexts": {"code": "
\nYour content goes here ..."}},"dataVersion": "2.0","properties": {"displayPreview": true,"lineWrapping": true,"miniMap": {"enabled": false},"previewState": "Show","theme": "Monokai"}}. Error: SyntaxError: Unexpected token 
 in JSON at position 91

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: `localm365 spo page clientsidewebpart add --webUrl "https://cpsglobaldev.sharepoint.com/teams/ValoDoctor" --pageName "Valo-Doctor.aspx" --webPartId 1ef5ed11-ce7b-44be-bc5e-4abd55101d16 --webPartData '{"title":"doctor-placeholder","serverProcessedContent": {"searchablePlainTexts": {"code": "\r\\nYour content goes here ..."}},"dataVersion": "2.0","properties": {"displayPreview": true,"lineWrapping": true,"miniMap": {"enabled": false},"previewState": "Show","theme": "Monokai"}}'`,
  context: [Object: null prototype] {
    files: [ '/home/vsts/work/1/s/src/index.md' ]
  }
}
```

**Comment by garrytrinder** [comment]
Running the command manually using latest version of CLI works though

**Comment by estruyf** [comment]
This is something else @garrytrinder. It is related to Windows and quotes within JSON. I've just found a solution to this. The first version with Windows support is available in beta: `npm i @valo/doctor@next -g`.

**Comment by garrytrinder** [comment]
> This is something else @garrytrinder. It is related to Windows and quotes within JSON. I've just found a solution to this. The first version with Windows support is available in beta: `npm i @valo/doctor@next -g`.

It might not be as I'm not using Windows, the error message was taken from an Azure DevOps build agent using `ubuntu-latest` base image.

For reference

```yaml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node@14'

- script: |
    npm i -g @pnp/cli-microsoft365@next
    npm i -g @valo/doctor@next
  displayName: 'Install CLI for Microsoft 365 & Valo Intranet Doctor'

- script: |
    doctor publish --url $(SPO_SITE_URL) --auth password --username $(DOCTOR_USER) --password $(DOCTOR_PASSWORD) --skipPrecheck
  displayName: 'Process markdown and publish pages to SharePoint Online'
```

Although I've just noticed that you are bundling the CLI with Doctor, so I could probably remove that part 😄

**Comment by estruyf** [comment]
Indeed, the reason is to make sure that the tool would not create version conflicts.

**Comment by estruyf** [comment]
Running builds and publishing on three different agents atm to verify if it keeps working: https://github.com/ValoIntranet/doctor/actions/runs/430660148

**Comment by estruyf** [comment]
Should have been fixed in version `1.2.0`. If not, feel free to open this issue or a new one.

**Comment by garrytrinder** [comment]
Still an issue on 1.2.0 unfortunately, raised a new issue #16 with details.
